# Generated by Django 2.2.7 on 2020-07-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Task_Type', '0001_initial'),
        ('User', '0001_initial'),
        ('Country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('active', models.CharField(default='Y', max_length=10)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Country.Country')),
                ('tasktype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task_Type.Task_Type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.User')),
            ],
            options={
                'db_table': 'Timezone_detail',
            },
        ),
    ]
